export interface SatTip {
  id: string;
  text: string;
  source: "College Board" | "Khan Academy" | "Princeton Review" | "Magoosh" | "Kaplan";
}

// Concise original study prompts based on the source guidance documented in docs/sat-tips-sources.md.
export const SAT_TIPS: SatTip[] = [
  { id: "format-1", text: "Take at least one full Bluebook practice test in one sitting before test day.", source: "College Board" },
  { id: "format-2", text: "Practice in the same digital format you will use on test day.", source: "College Board" },
  { id: "format-3", text: "Treat each module as final: you cannot return after its time expires.", source: "College Board" },
  { id: "format-4", text: "Use the question menu to flag an uncertain question, then return before the module ends.", source: "College Board" },
  { id: "format-5", text: "Try a pacing plan in practice before relying on it during the real test.", source: "College Board" },
  { id: "format-6", text: "Study in a quiet, desk-like setting sometimes so full tests feel familiar.", source: "College Board" },
  { id: "review-1", text: "After practice, sort misses by question type rather than reviewing them as one pile.", source: "Khan Academy" },
  { id: "review-2", text: "Read the explanation for every miss and name the reason you chose the wrong answer.", source: "Khan Academy" },
  { id: "review-3", text: "Work weak skills first, but mix in near-mastered skills to keep momentum.", source: "Khan Academy" },
  { id: "review-4", text: "Use a diagnostic or course challenge to find the skills worth your next study block.", source: "Khan Academy" },
  { id: "review-5", text: "Set one measurable goal for the next practice session, such as accuracy on one domain.", source: "Magoosh" },
  { id: "review-6", text: "Keep an error log: concept gap, misread, timing issue, or careless execution.", source: "Magoosh" },
  { id: "review-7", text: "Schedule regular practice instead of saving all review for one long cram session.", source: "Magoosh" },
  { id: "review-8", text: "Take real breaks during full practice so you build sustainable test-day focus.", source: "Magoosh" },
  { id: "rw-1", text: "Identify the question type before reading deeply; the task tells you what evidence matters.", source: "Princeton Review" },
  { id: "rw-2", text: "For main-idea questions, choose the claim that covers the whole passage, not one detail.", source: "Princeton Review" },
  { id: "rw-3", text: "For an inference, select only what the text supports; avoid answers that add a new claim.", source: "Princeton Review" },
  { id: "rw-4", text: "For evidence questions, require the answer to prove the claim, not merely mention its topic.", source: "Princeton Review" },
  { id: "rw-5", text: "For a word in context, test each choice in the sentence and preserve both meaning and tone.", source: "Princeton Review" },
  { id: "rw-6", text: "When two RW choices seem close, compare their strength: measured wording often matters.", source: "Princeton Review" },
  { id: "rw-7", text: "For a detail's function, label its job: example, contrast, concession, definition, or qualification.", source: "Princeton Review" },
  { id: "rw-8", text: "For transitions, decide the relationship first: addition, contrast, cause, example, or sequence.", source: "Magoosh" },
  { id: "rw-9", text: "For synthesis questions, cross out notes that do not serve the stated writing goal.", source: "Magoosh" },
  { id: "rw-10", text: "On grammar questions, compare only what changes among the choices to locate the rule being tested.", source: "Princeton Review" },
  { id: "rw-11", text: "Check that a verb agrees with its true subject, not the nearest noun.", source: "Princeton Review" },
  { id: "rw-12", text: "Use punctuation only when the surrounding clauses justify it; do not choose by pause alone.", source: "Princeton Review" },
  { id: "rw-13", text: "For pronouns, confirm that the reference is specific and agrees in number.", source: "Princeton Review" },
  { id: "rw-14", text: "For modifiers, make sure the opening phrase clearly attaches to the intended noun.", source: "Princeton Review" },
  { id: "rw-15", text: "For parallelism, keep items in a list or comparison in the same grammatical form.", source: "Princeton Review" },
  { id: "rw-16", text: "Read short, demanding nonfiction regularly and summarize its point in one sentence.", source: "Magoosh" },
  { id: "rw-17", text: "Use the passage's local context, not a dictionary's first definition, for vocabulary questions.", source: "Magoosh" },
  { id: "rw-18", text: "If an RW question stalls, flag it after a brief first pass and protect time for easier points.", source: "Princeton Review" },
  { id: "rw-19", text: "For graphs in RW, read the title, axes, and units before matching data to the claim.", source: "Khan Academy" },
  { id: "rw-20", text: "Translate a data claim into plain language before checking which choice matches the graph.", source: "Khan Academy" },
  { id: "math-1", text: "Use the built-in graphing calculator strategically; mental math can be faster for simple work.", source: "Khan Academy" },
  { id: "math-2", text: "Practice with the calculator you plan to use so its tools do not cost time on test day.", source: "Khan Academy" },
  { id: "math-3", text: "For an equation question, define the variable and write the relationship before calculating.", source: "Kaplan" },
  { id: "math-4", text: "Estimate first; an estimate can catch a sign error or an implausible calculator result.", source: "Kaplan" },
  { id: "math-5", text: "For a word problem, identify the quantity being asked for before choosing an operation.", source: "Kaplan" },
  { id: "math-6", text: "Keep units visible through the work, especially in rates, percentages, and conversions.", source: "Kaplan" },
  { id: "math-7", text: "For a table or graph, state the trend or rate in words before using numbers.", source: "Khan Academy" },
  { id: "math-8", text: "For percent change, use the original value as the denominator unless the question says otherwise.", source: "Kaplan" },
  { id: "math-9", text: "For linear equations, use slope as change in output over change in input.", source: "Khan Academy" },
  { id: "math-10", text: "For systems, decide whether substitution, elimination, a graph, or the calculator is quickest.", source: "Kaplan" },
  { id: "math-11", text: "For quadratics, check whether factoring, the vertex form, roots, or graphing best answers the question.", source: "Kaplan" },
  { id: "math-12", text: "Use the provided reference sheet, but know when a formula applies and what each symbol means.", source: "Magoosh" },
  { id: "math-13", text: "For geometry, draw or label the diagram yourself when that makes the relationships clearer.", source: "Magoosh" },
  { id: "math-14", text: "For a student-produced response, reread the requested form before submitting your answer.", source: "College Board" },
  { id: "math-15", text: "For a fraction response, simplify only when the question requires an equivalent exact form.", source: "Kaplan" },
  { id: "math-16", text: "Plug an answer back into the original relationship when verification is fast.", source: "Kaplan" },
  { id: "math-17", text: "Do not spend extra time on a hard Math problem before collecting the questions you can solve quickly.", source: "Khan Academy" },
  { id: "math-18", text: "When choices are numeric, backsolve or plug in simple values only when it is faster than algebra.", source: "Kaplan" }
];
